---
ID: "a4f9007e-1ed2-4821-b7a2-fae6aabcdbff"
Parent: "50a144ef-da0a-4a65-ae05-ebb192dc05cd"
Template: "fd2059fd-6043-4dfe-8c04-e2437ce87634"
Path: /sitecore/content/AndersenCorporation/AndersenWindows/AndersenWindows/Presentation/Partial Designs/Base
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: base
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        s:l="{DD2C902A-D7D2-4DB9-8538-C7748DAB080D}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221116T231617Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dfaac70c-b777-4da4-a964-26cf7e9a6d30"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221117T004221Z
