parameters:
  buildConfiguration: ''

steps:
# - task: Cache@2
#   displayName: Cache NuGet packages
#   inputs:
#     key: 'nuget | "$(Agent.OS)" | $(Build.SourcesDirectory)/src/platform/packages.lock.json'
#     restoreKeys: |
#        nuget | "$(Agent.OS)"
#        nuget
#     path: $(NUGET_PACKAGES)

- task: NuGetToolInstaller@1
  displayName: Install Nuget CLI

- task: NuGetCommand@2
  displayName: NuGet Restore
  inputs:
    restoreSolution: EnterpriseWeb.sln
    feedsToUse: config
    nugetConfigPath: $(Build.SourcesDirectory)\nuget.config

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: $(Build.SourcesDirectory)\src\platform\Platform.csproj
    msbuildArgs: /p:DeployonBuild=true /p:PublishProfile=DevOps
    configuration: ${{ parameters.buildConfiguration }}
    platform: AnyCPU
