---
ID: "0342efb8-148c-4afd-a979-eba247003c65"
Parent: "e8c3fa03-7128-48f1-b12d-674f2f2da133"
Template: "e8c3fa03-7128-48f1-b12d-674f2f2da133"
Path: /sitecore/templates/Feature/EnterpriseWeb/Components/Promo/Promo Swatches/Promo Swatch Collection/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230406T150718Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "7e2b7aad-b58f-4ce6-8e55-69f350d8ba2d"
      Hint: swatchStyle
      Value: "{8F986EE3-ACA9-4667-A04A-3E929D4BDB97}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "74c79c21-41b7-43ce-982a-e15ef3d6f7a4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230406T150727Z
