---
ID: "49f3cfdf-88fc-478b-8b6b-c430592e3066"
Parent: "969570f5-de11-4ce7-81a8-912cebba33f0"
Template: "969570f5-de11-4ce7-81a8-912cebba33f0"
Path: /sitecore/templates/Feature/EnterpriseWeb/Elements/Media/SVG Icon/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230203T193226Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "375c92f2-7b4e-411b-8906-1e53f4eba8c0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230203T193226Z
