trigger: none

variables:
  - group: 'Release Pipeline Variables - Dev'

resources:
  # pipelines:
  # - pipeline: build-dev # Name of the pipeline resource.
  #   source: Build-Dev # The name of the pipeline referenced by this pipeline resource.
  #   project: EnterpriseWeb # Required only if the source pipeline is in another project
  #   trigger:
  #     branches:
  #       include:
  #       - develop # Run pipeline when any run of Build-Dev completes on develop branch
  repositories:
  - repository: enterprise-deployment
    type: git
    name: enterprise-deployment

stages:
- stage: GetArtifactVersion
  jobs:
  - job: GetArtifactVersion
    displayName: "Get Deployment Package Version"
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: 'self'
    - template: 'azure-pipeline-step-get-package.yml'

- stage: DeployCM
  dependsOn:
  - GetArtifactVersion
  jobs:
  - deployment: DeployCM
    displayName: "CM Deployment"
    environment: 'BED-Dev'
    workspace:
      clean: all
    pool:
      name: AKS
      demands:
      - kubectl -equals 1.25.0
      - kubelogin -equals 0.0.20
      - AzureCLI -equals 2.42.0
    variables:
    - name: buildVersionToDownload
      value: $[ stageDependencies.GetArtifactVersion.GetArtifactVersion.outputs['GetPackageVersion.buildVersionToDownload'] ]
    - name: SitecoreBuildRevision
      value: $[ stageDependencies.GetArtifactVersion.GetArtifactVersion.outputs['GetPackageVersion.SitecoreBuildRevision'] ]
    - name: sitecore_environment
      value: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: 'enterprise-deployment'
          - checkout: 'self'
          - template: 'azure-pipeline-step-deploy-cm.yml'
            parameters:
              azsubscription: DEV_ENTWB1
  - job: HealthCheckAndSync
    dependsOn:
    - DeployCM
    displayName: "HealthCheck And Sync"
    workspace:
      clean: all
    pool:
      name: 'Enterprise Web'
#      demands:
#      - Purpose -equals SitecoreHealthCheckAnDotnetCommands
    variables:
    - name: buildVersionToDownload
      value: $[ stageDependencies.GetArtifactVersion.GetArtifactVersion.outputs['GetPackageVersion.buildVersionToDownload'] ]
    - name: SitecoreBuildRevision
      value: $[ stageDependencies.GetArtifactVersion.GetArtifactVersion.outputs['GetPackageVersion.SitecoreBuildRevision'] ]
    steps:
    - checkout: 'self'
    - checkout: 'enterprise-deployment'
    - template: 'azure-pipeline-step-deploy-common.yml'
      parameters:
        azsubscription: DEV_ENTWB1

- stage: DeployVercelAndersenWindows
  dependsOn:
  - GetArtifactVersion
  - DeployCM
  jobs:
  - deployment: DeployVercelAndersenWindows
    displayName: "Deploy Vercel AndersenWindows"
    environment: 'FED-Dev'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - name: buildVersionToDownload
      value: $[ stageDependencies.GetArtifactVersion.GetArtifactVersion.outputs['GetPackageVersion.buildVersionToDownload'] ]
    - name: SitecoreBuildRevision
      value: $[ stageDependencies.GetArtifactVersion.GetArtifactVersion.outputs['GetPackageVersion.SitecoreBuildRevision'] ]
    - name: VERCEL_PROJECT_ID
      value: prj_sgXutj2yEXZ9SEOiWAsidIa6iQ3G
    - name: application
      value: aw
    - name: alias_url
      value: andersenwindows-dev.vercel.app
    - name: VercelAppUrl
      value: https://andersenwindows-dev.vercel.app
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: 'self'
          - template: 'azure-pipeline-step-deploy-vercel.yml'

- stage: DeployVercelRenewalByAndersen
  dependsOn:
  - GetArtifactVersion
  - DeployCM
  jobs:
  - deployment: DeployVercelRenewalByAndersen
    displayName: "Deploy Vercel RenewalByAndersen"
    environment: 'FED-Dev'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - name: buildVersionToDownload
      value: $[ stageDependencies.GetArtifactVersion.GetArtifactVersion.outputs['GetPackageVersion.buildVersionToDownload'] ]
    - name: SitecoreBuildRevision
      value: $[ stageDependencies.GetArtifactVersion.GetArtifactVersion.outputs['GetPackageVersion.SitecoreBuildRevision'] ]
    - name: VERCEL_PROJECT_ID
      value: prj_nbEjEAvh75SSSkcOBDvlHzTHlU1c
    - name: application
      value: rba
    - name: alias_url
      value: renewalbyandersen-dev.vercel.app
    - name: VercelAppUrl
      value: https://renewalbyandersen-dev.vercel.app
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: 'self'
          - template: 'azure-pipeline-step-deploy-vercel.yml'
