steps:
#Getting Selected version of Packages
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "BuildVersionToDownload is: " $(buildVersionToDownload)
      echo "SitecoreBuildRevision is: " $(SitecoreBuildRevision)
  displayName: 'Getting Selected Package Versions'

#Download package to agent directory
- template: 'azure-pipeline-step-add-artifacts.yml'

#Getting version of Deployment Packages
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "Your selected Web Package Version is: " $(NugetVersion)
      echo "BuildVersionToDownload is: " $(GetPackageVersion.buildVersionToDownload)
      echo "SitecoreBuildRevision is: " $(GetPackageVersion.SitecoreBuildRevision)
  displayName: 'Getting Final Deployment Package Versions'
