---
ID: "fc7b001a-6234-4b4c-bd14-9fdce82b01d3"
Parent: "9b6b65b9-3c42-4261-b9fe-1ae9fd5c124c"
Template: "d2923fee-da4e-49be-830c-e27764dfa269"
Path: /sitecore/system/Settings/Feature/EnterpriseWeb/Enums/Search/Facet Fields/Product Type
SharedFields:
- ID: "f917c951-1f75-4d62-b14a-bc6888d7eeca"
  Hint: Value
  Value: ew_producttype
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230405T170322Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b49e3707-19e6-4812-a75f-8e6c0ce796e3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230419T055738Z
