---
ID: "14499840-2da3-4abc-a75e-2112f5d0c4c0"
Parent: "c016ebff-6b7e-4f31-9b1f-5274d056b64a"
Template: "c016ebff-6b7e-4f31-9b1f-5274d056b64a"
Path: /sitecore/templates/Feature/EnterpriseWeb/Components/Listing/List Image with Callouts/List Image with Callouts/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{E9DE8594-3A46-43E2-80E5-D2CFCE395DDF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221129T171257Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "99b2b376-7896-44d0-9ce3-5b2dfbb297e1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221206T193658Z
