---
ID: "15b3b2e8-7b06-4210-b4fe-8b017d045ae1"
Parent: "b2cd1d89-2d2b-4b4c-81ce-abcc07566e32"
Template: "15665680-e4a6-45ba-98e8-4b46a33b7a2d"
Path: /sitecore/templates/Branches/Feature/EnterpriseWeb/Product Folder/$name/Products
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221215T200834Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e347a68c-eb9f-47d0-9724-99dcfe345c5d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221215T200834Z
